[package]
name = "ruma-bot-macro"
version = "0.1.0"
authors = ["Jonas Platte <jplatte+git@posteo.de>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4.30"
quote = "0.6.13"

[dependencies.syn]
version = "0.15.40"
features = ["full", "extra-traits"]