[package]
name = "ruma-bot-macros"
version = "0.1.0"
authors = ["Jonas Platte <jplatte+git@posteo.de>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.6"
quote = "1.0.2"

[dependencies.syn]
version = "1.0.8"
features = ["full", "extra-traits"]
